const modal=document.querySelector('#modal'),toast=document.querySelector('#toast');let db,functions,timer;
const notice=m=>{toast.textContent=m;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),3200)};
const load=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.append(s)});
const open=type=>{modal.dataset.type=type;document.querySelector('#modalTitle').textContent=type==='fertigation'?'Prepare fertigation':'Review irrigation';document.querySelector('#confirm').textContent=type==='fertigation'?'Continue to recipe':'Request irrigation';modal.classList.add('open');modal.setAttribute('aria-hidden','false')};
const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
function updateNode(id,reading){const node=document.querySelector(`[data-node="${id}"]`);if(!node||!reading)return;const detail=node.querySelector('small');if(reading.valid!==true){node.classList.remove('healthy','warning');node.classList.add('error');detail.textContent='Sensor error';return}const low=Number(reading.moisture)<22;node.classList.toggle('warning',low);node.classList.toggle('healthy',!low);detail.textContent=`${Number(reading.moisture).toFixed(1)}% moisture`;}
async function init(){try{await load('firebase-config.js');if(!window.FIREBASE_CONFIG||window.FIREBASE_CONFIG.projectId==='YOUR_PROJECT_ID'){notice('Demo mode — add Firebase web configuration to connect a farm.');return}await Promise.all(['firebase-app-compat.js','firebase-auth-compat.js','firebase-database-compat.js','firebase-functions-compat.js'].map(name=>load(`https://www.gstatic.com/firebasejs/10.12.2/${name}`)));firebase.initializeApp(window.FIREBASE_CONFIG);db=firebase.database();functions=firebase.functions();firebase.auth().onAuthStateChanged(user=>{if(!user){notice('Sign in to view production telemetry and request operations.');return}['NODE_01','NODE_02','NODE_03','NODE_04'].forEach(id=>db.ref(`stands/STAND_01/nodes/${id}/current`).on('value',s=>updateNode(id,s.val())));db.ref('operations').orderByChild('requested_by').equalTo(user.uid).limitToLast(10).on('child_changed',s=>{const op=s.val();if(op.status==='FAILED')notice(`Operation failed: ${op.error_message||op.error_code||'controller reported a failure'}`);if(op.status==='COMPLETED')notice(`Operation ${op.operation_id} completed.`)})})}catch(error){console.warn(error);notice('Firebase connection could not be initialized.')}}
async function requestOperation(){const button=document.querySelector('#confirm'),target=document.querySelector('#target').value.split(' / ')[1],waterLiters=Number(document.querySelector('#liters').value),type=modal.dataset.type;if(!Number.isFinite(waterLiters)||waterLiters<=0)return notice('Enter a valid water quantity.');if(!functions)return notice('Sign in and configure Firebase before sending an operation request.');button.disabled=true;button.textContent='Validating…';try{const callable=functions.httpsCallable(type==='fertigation'?'createFertigationOperation':'createIrrigationOperation');const payload={standId:'STAND_01',targetNodes:[target],waterLiters};if(type==='fertigation')payload.dosing={nitrogen_ml:0,phosphorus_ml:0,potassium_ml:0};const response=await callable(payload);close();notice(`Operation ${response.data.operationId} accepted. Status: PENDING.`)}catch(error){notice(error.message||'Operation request was rejected.')}finally{button.disabled=false;button.textContent=type==='fertigation'?'Continue to recipe':'Request irrigation'}}
document.querySelector('#irrigate').onclick=()=>open('irrigation');document.querySelector('#fertigate').onclick=()=>open('fertigation');document.querySelector('.close').onclick=close;document.querySelector('.cancel').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelector('#confirm').onclick=requestOperation;document.querySelectorAll('.node').forEach(n=>n.onclick=()=>notice(`${n.dataset.node}: select Stand view for full current and historical readings.`));document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active')});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.querySelector('#stand').onclick=()=>notice('Stand detail is ready for the selected monitoring zone.');document.querySelector('#allAlerts').onclick=()=>notice('Alert center selected.');init();
