"use client";

import { limitToLast, onValue, orderByChild, query, ref } from "firebase/database";
import { useEffect, useMemo, useState } from "react";
import { appCheckHeader, firebaseAuth, firebaseConfigured, firebaseDatabase } from "../lib/firebase/client";
import { useAuthSessionVersion } from "../lib/firebase/use-auth-session";

type Alert = { alert_id: string; type: string; severity: "WARNING" | "CRITICAL" | string; node_id?: string; message: string; created_at?: number; updated_at?: number; resolved?: boolean; acknowledged?: boolean };

export function AlertFeed({ farmId }: { farmId: string }) {
  const [alerts, setAlerts] = useState<Alert[]>([]); const [acknowledging, setAcknowledging] = useState<string | null>(null); const [message, setMessage] = useState(""); const [readError, setReadError] = useState(""); const authSessionVersion = useAuthSessionVersion();
  useEffect(() => { if (!firebaseDatabase) return; const source = query(ref(firebaseDatabase, `farms/${farmId}/alerts`), orderByChild("created_at"), limitToLast(20)); return onValue(source, snapshot => { const value = snapshot.val() as Record<string, Alert> | null; setReadError(""); setAlerts(value ? Object.entries(value).map(([alertId, alert]) => ({ ...alert, alert_id: alert.alert_id || alertId })).sort((a, b) => (b.updated_at ?? b.created_at ?? 0) - (a.updated_at ?? a.created_at ?? 0)) : []); }, () => { setAlerts([]); setReadError("Sign in to load authorized field alerts."); }); }, [farmId, authSessionVersion]);
  const unresolved = useMemo(() => alerts.filter(alert => !alert.resolved), [alerts]);
  async function acknowledge(alertId: string) { const user = firebaseAuth?.currentUser; if (!user) return setMessage("Sign in to acknowledge alerts."); setAcknowledging(alertId); setMessage(""); try { const token = await user.getIdToken(); const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/api/farms/${farmId}/alerts/${alertId}/acknowledge`, { method: "POST", headers: { Authorization: `Bearer ${token}`, ...await appCheckHeader() } }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "ACKNOWLEDGEMENT_FAILED"); setMessage("Alert acknowledged."); } catch (error) { setMessage(error instanceof Error ? error.message : "ACKNOWLEDGEMENT_FAILED"); } finally { setAcknowledging(null); } }
  return <section className="panel"><div className="section-head"><div><p className="eyebrow">ALERTS</p><h2>Field conditions needing review</h2></div><span className="badge">{unresolved.length} open</span></div>{!firebaseConfigured ? <p className="lede">Configure Firebase to receive field alerts.</p> : readError ? <p className="lede">{readError}</p> : !alerts.length ? <p className="lede">No alerts have been recorded for this Farm.</p> : <ul>{alerts.map(alert => <li key={alert.alert_id}><strong>{alert.resolved ? "Resolved" : alert.acknowledged ? "Acknowledged" : alert.severity} · {alert.type}</strong><span>{alert.node_id ? `${alert.node_id} · ` : ""}{alert.message}</span><small>{alert.updated_at ?? alert.created_at ? new Date(alert.updated_at ?? alert.created_at!).toLocaleString() : "Timestamp unavailable"}</small>{!alert.resolved && !alert.acknowledged ? <button type="button" className="quiet-button" onClick={() => void acknowledge(alert.alert_id)} disabled={acknowledging === alert.alert_id}>{acknowledging === alert.alert_id ? "Acknowledging…" : "Acknowledge"}</button> : null}</li>)}</ul>}{message ? <p role="status" data-tone="idle">{message}</p> : null}</section>;
}
