"use client";

import { useState } from "react";
import { appCheckHeader, firebaseAuth, firebaseConfigured } from "../lib/firebase/client";

type Result = { tone: "idle" | "success" | "error"; message: string };
type OperationKind = "IRRIGATE" | "FERTIGATE";
const initialResult: Result = { tone: "idle", message: "Sign in with Firebase to request an operation." };
const configuredMaximum = Number(process.env.NEXT_PUBLIC_MAX_IRRIGATION_LITERS ?? 20);
const maxWaterLiters = Number.isFinite(configuredMaximum) && configuredMaximum > 0 ? configuredMaximum : 20;

export function OperationForm({ farmId, standId }: { farmId: string; standId: string }) {
  const [kind, setKind] = useState<OperationKind>("IRRIGATE"); const [nodeId, setNodeId] = useState("NODE_01"); const [liters, setLiters] = useState("5"); const [nitrogen, setNitrogen] = useState("0"); const [phosphorus, setPhosphorus] = useState("0"); const [potassium, setPotassium] = useState("0"); const [pending, setPending] = useState(false); const [result, setResult] = useState<Result>(initialResult);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const waterLiters = Number(liters); const dose = { nitrogen: Number(nitrogen), phosphorus: Number(phosphorus), potassium: Number(potassium) }; if (!Number.isFinite(waterLiters) || waterLiters <= 0 || waterLiters > maxWaterLiters) return setResult({ tone: "error", message: `Enter 0.1–${maxWaterLiters} litres for this request.` }); if (kind === "FERTIGATE" && Object.values(dose).some(value => !Number.isFinite(value) || value < 0 || value > 100)) return setResult({ tone: "error", message: "Enter each nutrient dose between 0 and 100 ml." }); const user = firebaseAuth?.currentUser; if (!user) return setResult({ tone: "error", message: firebaseConfigured ? "Sign in before requesting an operation." : "Configure Firebase before requesting an operation." }); setPending(true); setResult({ tone: "idle", message: "Validating target and controller status…" }); try { const token = await user.getIdToken(); const response = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}/api/commands/${kind === "IRRIGATE" ? "irrigate" : "fertigate"}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...await appCheckHeader() }, body: JSON.stringify({ farmId, standId, targetNodes: [nodeId], waterLiters, ...(kind === "FERTIGATE" ? { dosingMl: dose } : {}) }) }); const body = await response.json() as { operationId?: string; error?: string; max_liters?: number }; if (!response.ok) throw new Error(body.error === "MAX_IRRIGATION_EXCEEDED" ? `Maximum is ${body.max_liters} litres.` : body.error ?? "REQUEST_REJECTED"); setResult({ tone: "success", message: `Operation ${body.operationId} is PENDING. Completion requires device acknowledgement.` }); } catch (error) { setResult({ tone: "error", message: error instanceof Error ? error.message : "REQUEST_FAILED" }); } finally { setPending(false); } }
  return <section className="panel"><p className="eyebrow">NEW FIELD REQUEST</p><h2>Request a measured delivery</h2><form onSubmit={submit}><label>Operation type<select value={kind} onChange={event => setKind(event.target.value as OperationKind)}><option value="IRRIGATE">Irrigation</option><option value="FERTIGATE">Fertigation</option></select></label><label>Target node<select value={nodeId} onChange={event => setNodeId(event.target.value)}>{Array.from({ length: 6 }, (_, index) => <option key={index} value={`NODE_${String(index + 1).padStart(2, "0")}`}>{`NODE_${String(index + 1).padStart(2, "0")}`}</option>)}</select></label><label>Water target (litres)<input value={liters} inputMode="decimal" max={maxWaterLiters} onChange={event => setLiters(event.target.value)} /></label>{kind === "FERTIGATE" ? <fieldset style={{ border: 0, padding: 0, margin: 0, display: "grid", gap: 12 }}><legend className="eyebrow" style={{ marginTop: 4 }}>NUTRIENT DOSE (ML)</legend><label>Nitrogen<input value={nitrogen} inputMode="decimal" onChange={event => setNitrogen(event.target.value)} /></label><label>Phosphorus<input value={phosphorus} inputMode="decimal" onChange={event => setPhosphorus(event.target.value)} /></label><label>Potassium<input value={potassium} inputMode="decimal" onChange={event => setPotassium(event.target.value)} /></label></fieldset> : null}<button type="submit" disabled={pending}>{pending ? "Creating request…" : `Request ${kind === "IRRIGATE" ? "irrigation" : "fertigation"}`}</button></form><p role="status" data-tone={result.tone}>{result.message}</p></section>;
}
